// Generated by https://quicktype.io

export interface AddAttachmentToRecordID {
    METADATA_ATTACHTOEMAIL: string;
    METADATA_CREATEDBY:     string;
    METADATA_CREATEDDATE:   string;
    METADATA_EXTENSION:     string;
    METADATA_FILENAME:      string;
    METADATA_SIZE:          string;
    METADATA_TENANTID:      string;
    METADATA_URL:           string;
    Type:                   string;
    ViewNameFriendly:       string;
    RecordId:               RecordID;
    Url:                    URL;
    AttachToEmail:          AttachToEmail;
    Notes:                  string;
    ActionId:               number;
    Disabled:               boolean;
    InValid:                boolean;
    ValidationMessages:     any[];
    Metadata:               null;
}

export interface AttachToEmail {
    ValueType:         number;
    Value:             boolean;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}

export interface RecordID {
    ValueType:         number;
    Value:             number;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}

export interface URL {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
