// Generated by https://quicktype.io

export interface CallRoutine {
    ActionSetId:         string;
    AppRoutineId:        string;
    AppRoutineVersionId: string;
    InputValues:         any[];
    OutputValues:        any[];
    IsSync:              boolean;
    CustomMessage:       null;
    ShowMessage:         boolean;
    Type:                string;
    Notes:               string;
    ActionId:            number;
    Disabled:            boolean;
    InValid:             boolean;
    ValidationMessages:  any[];
    Metadata:            null;
}
