// Generated by https://quicktype.io

export interface CallWebService {
    Headers:            Header[];
    Params:             Header[];
    Payload:            Payload;
    ResultToSet:        ToSet;
    StatusCodeToSet:    ToSet;
    Type:               string;
    Checked:            boolean;
    Function:           null;
    Url:                string;
    HttpMethod:         number;
    WebServiceType:     number;
    ContentType:        number;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface Header {
    Key:   string;
    Value: Payload;
}

export interface Payload {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null | string;
    FontStyles:        null;
}

export interface ToSet {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   null;
    ValidationMessages: any[];
}
