// Generated by https://quicktype.io

export interface CheckPermission {
    Type:               string;
    AppId:              string;
    Permission:         number;
    DenialMessage:      null;
    ShowMessage:        boolean;
    User:               User;
    ResultToSet:        ResultToSet;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface ResultToSet {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   string;
    ValidationMessages: any[];
}

export interface User {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
