// Generated by https://quicktype.io

export interface DeleteRecordsFromTable {
    ViewNameFriendly:   string;
    Type:               string;
    WhereClause:        WhereClause[];
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface WhereClause {
    Operation:         number | null;
    DateField:         null;
    Source:            Source | null;
    AdditionalSources: null;
    DateWhere:         null;
}

export interface Source {
    ValueType:         number;
    Value:             number | string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
