// Generated by https://quicktype.io

export interface GenerateReport {
    Type:               string;
    ReportName:         string;
    ReportDisplayName:  Report;
    ReportNameOverride: Report;
    ViewFriendlyName:   string;
    WhereClause:        WhereClause[];
    SafeGuard:          number;
    ReportType:         number;
    DisplayReport:      boolean;
    ResultToSet:        ResultToSet;
    OptimizeFields:     boolean;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface Report {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}

export interface ResultToSet {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   string;
    ValidationMessages: any[];
}

export interface WhereClause {
    Operation:         number | null;
    DateField:         null;
    Source:            Source | null;
    AdditionalSources: null;
    DateWhere:         null;
}

export interface Source {
    ValueType:         number;
    Value:             number | string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
