// Generated by https://quicktype.io

export interface InsertRecordsIntoTable {
    Type:               string;
    Fields:             Field[];
    InsertType:         number;
    SourceRecordId:     Source;
    ViewNameFriendly:   string;
    ResultToSet:        ResultToSet;
    FieldsToOmit:       any[];
    IncludeDocuments:   boolean;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface Field {
    Field:  string;
    Source: Source;
}

export interface Source {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null | string;
    FontStyles:        null;
}

export interface ResultToSet {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   string;
    ValidationMessages: any[];
}
