// Generated by https://quicktype.io

export interface MappingFunctions {
    Type:                string;
    MappingAction:       number;
    ViewNameFriendly:    string;
    MapWidget:           null;
    AddressLine1:        string;
    AddressLine2:        string;
    AddressLine3:        string;
    City:                string;
    State:               string;
    PostalCode:          string;
    Country:             string;
    RecordIds:           End;
    OptimizeRoute:       boolean;
    UpdateRouteField:    null;
    IsStartEndSpecified: boolean;
    Start:               End;
    End:                 End;
    Notes:               string;
    ActionId:            number;
    Disabled:            boolean;
    InValid:             boolean;
    ValidationMessages:  any[];
    Metadata:            null;
}

export interface End {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null | string;
    FontStyles:        null;
}
