// Generated by https://quicktype.io

export interface MathFunctions {
    Type:               string;
    Values:             Value[];
    ControlToUpdate:    null;
    ResultToSet:        ResultToSet;
    MathFunctionType:   number;
    Rounding:           number;
    DecimalPlaces:      number;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface ResultToSet {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   string;
    ValidationMessages: any[];
}

export interface Value {
    ValueType:         number;
    Value:             number;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
