// Generated by https://quicktype.io

export interface MergeEntitiesContacts {
    Type:                string;
    MergeType:           number;
    FromRecordID:        RecordID;
    ToRecordID:          RecordID;
    AccountingRequested: boolean;
    Notes:               string;
    ActionId:            number;
    Disabled:            boolean;
    InValid:             boolean;
    ValidationMessages:  any[];
    Metadata:            null;
}

export interface RecordID {
    ValueType:         number;
    Value:             number;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
