// Generated by https://quicktype.io

export interface PrepareForAccounting {
    Type:               string;
    SyncOverride:       boolean;
    WhereClause:        WhereClause[];
    ViewNameFriendly:   string;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface WhereClause {
    Operation:         number | null;
    DateField:         null;
    Source:            Source | null;
    AdditionalSources: null;
    DateWhere:         null;
}

export interface Source {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null | string;
    FontStyles:        null;
}
