// Generated by https://quicktype.io

export interface ProcessPayment {
    Type:                        string;
    ActionType:                  number;
    Using:                       number;
    AnalyticsPaymentAction:      string;
    Amount:                      Amount;
    Currency:                    Currency;
    CurrencyOption:              string;
    EntityId:                    Currency;
    ReferenceNumber:             Currency;
    StoredPayment:               Currency;
    SaveCardOption:              number;
    ConfiguredPaymentMethods:    number;
    IsSpecificEntity:            boolean;
    ActionResultGatewayResponse: ActionResult;
    ActionResultSuccessOrFail:   ActionResult;
    ActionResultReferenceNumber: ActionResult;
    Notes:                       string;
    ActionId:                    number;
    Disabled:                    boolean;
    InValid:                     boolean;
    ValidationMessages:          any[];
    Metadata:                    null;
}

export interface ActionResult {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   null;
    ValidationMessages: any[];
}

export interface Amount {
    ValueType:         number;
    Value:             number;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}

export interface Currency {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null | string;
    FontStyles:        null;
}
