// Generated by https://quicktype.io

export interface RefreshControl {
    Type:               string;
    ControlsToRefresh:  ControlsToRefresh[];
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface ControlsToRefresh {
    ControlId:          string;
    ClearCheckboxes:    boolean;
    IncludeData:        boolean;
    ValidationMessages: any[];
}
