// Generated by https://quicktype.io

export interface RetrieveValuesFromTable {
    ViewNameFriendly:   string;
    Type:               string;
    WhereClause:        WhereClause[];
    AggregationType:    number;
    Bindings:           Binding[];
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface Binding {
    FieldName:       string;
    ControlToUpdate: null;
    ResultToSet:     ResultToSet;
    UpdateControl:   boolean;
}

export interface ResultToSet {
    Source:             Source;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   string;
    ValidationMessages: any[];
}

export interface WhereClause {
    Operation:         number | null;
    DateField:         null;
    Source:            Source | null;
    AdditionalSources: null;
    DateWhere:         null;
}

export interface Source {
    ValueType:         number;
    Value:             number | string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
