// Generated by https://quicktype.io

export interface RetrieveExchangeRate {
    Type:               string;
    CurrencyCode:       AsOfDate;
    AsOfDate:           AsOfDate;
    ControlToUpdate:    null;
    ResultToSet:        ResultToSet;
    UpdateControl:      boolean;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface AsOfDate {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}

export interface ResultToSet {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   string;
    ValidationMessages: any[];
}
