// Generated by https://quicktype.io

export interface RetrieveValueFromEmailGadget {
    Type:               string;
    Bindings:           Binding[];
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface Binding {
    ValueName:       number;
    ControlToUpdate: null;
    ResultToSet:     ResultToSet;
    UpdateControl:   boolean;
}

export interface ResultToSet {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   string;
    ValidationMessages: any[];
}
