// Generated by https://quicktype.io

export interface SaveAll {
    Type:                     string;
    ValidateControlsOnScreen: boolean;
    Notes:                    string;
    ActionId:                 number;
    Disabled:                 boolean;
    InValid:                  boolean;
    ValidationMessages:       any[];
    Metadata:                 null;
}
