// Generated by https://quicktype.io

export interface SendEmail {
    Type:               string;
    From:               BatchName;
    FromName:           BatchName;
    To:                 BatchName;
    CC:                 null;
    BCC:                null;
    Subject:            BatchName;
    Message:            BatchName;
    Priority:           number;
    Server:             null;
    Username:           null;
    Password:           null;
    Port:               null;
    Attachments:        any[];
    ContactRecordId:    BatchName;
    BatchName:          BatchName;
    EmailType:          number;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface BatchName {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
