// Generated by https://quicktype.io

export interface SetFocusToControl {
    Type:               string;
    ControlId:          string;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}
