// Generated by https://quicktype.io

export interface ShowMessage {
    Type:               string;
    Message:            string;
    MessageParameters:  any[];
    Buttons:            string;
    Title:              string;
    ResultToSet:        ResultToSet;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface ResultToSet {
    Source:             null;
    ActionResultId:     string;
    IsSharedResult:     boolean;
    ActionResultName:   null;
    ValidationMessages: any[];
}
