// Generated by https://quicktype.io

export interface UpdateFieldsInTable {
    Fields:             Field[];
    ViewNameFriendly:   string;
    Type:               string;
    WhereClause:        WhereClause[];
    IsSaveAll:          boolean;
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface Field {
    Field:  string;
    Source: FieldSource;
}

export interface FieldSource {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}

export interface WhereClause {
    Operation:         number | null;
    DateField:         null;
    Source:            WhereClauseSource | null;
    AdditionalSources: null;
    DateWhere:         null;
}

export interface WhereClauseSource {
    ValueType:         number;
    Value:             number | string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
