// Generated by https://quicktype.io

export interface UpdateControlsOnScreen {
    Type:               string;
    ControlsToUpdate:   ControlsToUpdate[];
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface ControlsToUpdate {
    ControlId:          string;
    Property:           null;
    Source:             Source;
    ValidationMessages: any[];
}

export interface Source {
    ValueType:         number;
    Value:             string;
    Property:          string;
    ChildProperty:     null;
    ValidationMessage: null;
    FontStyles:        null;
}
