// Generated by https://quicktype.io

export interface UpdateEditableGridReadOnlyProperty {
    Type:               string;
    ControlsToUpdate:   ControlsToUpdate[];
    Notes:              string;
    ActionId:           number;
    Disabled:           boolean;
    InValid:            boolean;
    ValidationMessages: any[];
    Metadata:           null;
}

export interface ControlsToUpdate {
    ControlId:          string;
    ToggleOptions:      number;
    ValidationMessages: any[];
}
