// Generated by https://quicktype.io

export interface ValidateControlsOnScreen {
    Type:                string;
    IgnoreDataTable:     boolean;
    ValidateAllControls: boolean;
    ControlsToValidate:  any[];
    ValidateSingleRow:   number;
    Notes:               string;
    ActionId:            number;
    Disabled:            boolean;
    InValid:             boolean;
    ValidationMessages:  any[];
    Metadata:            null;
}
