export const DateFunctionTypes: string[] = [
    "blank",
    "Format Date",
    "Year",
    "Month",
    "Day",
    "Hour",
    "Minute",
    "Day of Week",
    "Day of Year",
    "First Day of Month",
    "Last Day of Month",
    "Other Date for Day",
    "Add Years",
    "Add Months",
    "Add Days",
    "Add Hours",
    "Add Minutes",
    "Date Difference",
    "Convert to UTC",
];