export const TextFunctionType: string[] = [
    "blank",
    "Find In Json",
    "Find In Text",
    "IsDate",
    "Is Email Address",
    "Is Empty",
    "Is Numberic",
    "Join",
    "Left",
    "Right",
    "Middle",
    "Length",
    "Replace",
    "Replace Merge Fields",
    "To Lower Case",
    "To Upper Case",
    "To Title Case",
    "Is Email Address"
];